import type { Provenance } from "./sources/freshness";

export type LangCode = "en" | "hi" | "ta" | "te" | "kn" | "ml";

/**
 * Text with translations for some languages and always an English original.
 *
 * Answers are generated by the model, so they arrive in whatever language the
 * member used. Interface chrome is hand-translated, and that lags — so lookups
 * fall back to English rather than rendering blank. Partial coverage of the UI
 * is acceptable; a missing string is not.
 */
export type LocalizedText = Partial<Record<LangCode, string>> & { en: string };

export type AgentId = "cooperative_law" | "schemes" | "pmfby" | "grievance";

export interface KnowledgeEntry {
  id: string;
  agent: AgentId;
  keywords: Partial<Record<LangCode, string[]>> & { en: string[] };
  source: string;
  answer: LocalizedText;
}

export interface ChatMessage {
  id: string;
  role: "user" | "assistant" | "system";
  text: string;
  /**
   * The language `text` is actually written in — which is what selects the
   * speech voice, so it must never be set to the language the member asked in
   * unless the text really is in it.
   */
  lang: LangCode;
  agent?: AgentId;
  source?: string;
  /**
   * How far this answer can be trusted right now, and why.
   *
   * Attached to the message rather than looked up at render time, because the
   * same message is rendered on a screen, read aloud, and printed on a
   * receipt — and all three must agree. A verdict recomputed separately per
   * surface is a verdict that will eventually disagree with itself, and a
   * printout that says something the screen did not is worse than no printout.
   */
  provenance?: Provenance;
  /**
   * Corpus passage the answer rests on.
   *
   * Carried so the kiosk can ask for a receipt pointing at it. The receipt is
   * a pointer to this id and nothing else, which is what lets a scan re-check
   * the rule instead of replaying whatever was true on the day it printed.
   */
  passageId?: string;
  /**
   * What a speaking channel should say — the answer with its caveat and the
   * free-service line already folded in.
   *
   * Kept separate from `text` because the screen shows the caveat as its own
   * element and would otherwise say it twice.
   */
  spokenText?: string;
  escalated?: boolean;
  /** True when the text came from the LLM rather than a stored passage. */
  generated?: boolean;
  /** True when a stored English passage was machine-translated into `lang`. */
  translated?: boolean;
  /** True when answered by the on-device fallback (server unreachable). */
  offline?: boolean;
  ticketId?: string;
  timestamp: number;
}

export type GrievanceStatus = "open" | "in_progress" | "resolved";

export interface Grievance {
  ticketId: string;
  name: string;
  phone: string;
  pacsName: string;
  category: string;
  description: string;
  status: GrievanceStatus;
  lang: LangCode;
  channel: "app" | "web" | "kiosk" | "ivr";
  createdAt: number;
  updatedAt: number;
}

export interface QueryLogEntry {
  id: string;
  agent: AgentId;
  lang: LangCode;
  resolved: boolean;
  channel: "app" | "web" | "kiosk" | "ivr";
  timestamp: number;
}
